export const envSchema = {
  type: "object",
  required: [
    "PORT",
    "HOSTNAME",
    "NODE_ENV",
    "ADMIN_API_KEY",
    "MYSQL_HOST",
    "MYSQL_PORT",
    "MYSQL_USER",
    "MYSQL_PASSWORD",
    "MYSQL_DB",
    "REDIS_HOST",
    "REDIS_PORT",
    "JWT_SECRET",
  ],
  properties: {
    PORT: { type: "string", pattern: "^[0-9]+$" },
    HOSTNAME: { type: "string", minLength: 1 },
    NODE_ENV: { type: "string", enum: ["development", "production"] },
    ADMIN_API_KEY: { type: "string", minLength: 1 },
    MYSQL_HOST: { type: "string", minLength: 1 },
    MYSQL_PORT: { type: "string", pattern: "^[0-9]+$" },
    MYSQL_USER: { type: "string", minLength: 1 },
    MYSQL_PASSWORD: { type: "string", minLength: 1 },
    MYSQL_DB: { type: "string", minLength: 1 },
    REDIS_URL: { type: "string", minLength: 1 },
    REDIS_HOST: { type: "string", minLength: 1 },
    REDIS_PORT: { type: "string", pattern: "^[0-9]+$" },
    JWT_SECRET: { type: "string", minLength: 32 },
    SESSION_SECRET: { type: "string", minLength: 32 },
    EXTERNAL_BASE_URL: { type: "string", minLength: 1 },
    GITHUB_TOKEN: { type: "string", minLength: 1 },
  },
  additionalProperties: true,
};
